[0m[35mPROMETHEUS: [0mApplying Obfuscation Pipeline to ../dist/bundle.lua ...
[0m[35mPROMETHEUS: [0mParsing ...
[0m[33mPROMETHEUS: Warning at Position 3321:19, the variable "requireRemote" is already defined in that scope[0m
[0m[35mPROMETHEUS: [0mParsing Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Encrypt Strings" ...
[0m[35mPROMETHEUS: [0mStep "Encrypt Strings" Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Anti Tamper" ...
[0m[35mPROMETHEUS: [0mStep "Anti Tamper" Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Vmify" ...
[0m[35mPROMETHEUS: [0mStep "Vmify" Done in 1.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Constant Array" ...
[0m[35mPROMETHEUS: [0mStep "Constant Array" Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Numbers To Expressions" ...
[0m[35mPROMETHEUS: [0mStep "Numbers To Expressions" Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mApplying Step "Wrap in Function" ...
[0m[35mPROMETHEUS: [0mStep "Wrap in Function" Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mRenaming Variables ...
[0m[35mPROMETHEUS: [0mRenaming Done in 0.00 seconds
[0m[35mPROMETHEUS: [0mGenerating Code ...
[0m[35mPROMETHEUS: [0mCode Generation Done in 1.00 seconds
[0m[35mPROMETHEUS: [0mObfuscation Done in 2.00 seconds
[0m[35mPROMETHEUS: [0mGenerated Code size is 421.12% of the Source Code size
[0m[35mPROMETHEUS: [0mWriting output to "../dist/bundle.obfuscated.lua"
